// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Product {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  content?: PortableTextBlock[];
  product_type?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery?: unknown;
  price: number;
  compare_at_price?: number;
  currency?: string;
  sku?: string;
  track_inventory?: boolean;
  stock_quantity?: number;
  weight_grams?: number;
  dimensions?: unknown;
  tax_category?: string;
  variants?: unknown;
  bundle_items?: unknown;
  digital_asset?: unknown;
  attributes?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    products: Product;
  }
}